INSERT INTO roles (name)
SELECT 'ROLE_ADMIN'
WHERE NOT EXISTS (
    SELECT 1 FROM roles WHERE name = 'ROLE_ADMIN'
);

INSERT INTO roles (name)
SELECT 'ROLE_COORDINATOR'
WHERE NOT EXISTS (
    SELECT 1 FROM roles WHERE name = 'ROLE_COORDINATOR'
);

INSERT INTO roles (name)
SELECT 'ROLE_NUTRITIONIST'
WHERE NOT EXISTS (
    SELECT 1 FROM roles WHERE name = 'ROLE_NUTRITIONIST'
);

INSERT INTO roles (name)
SELECT 'ROLE_PSYCHOLOGIST'
WHERE NOT EXISTS (
    SELECT 1 FROM roles WHERE name = 'ROLE_PSYCHOLOGIST'
);

INSERT INTO roles (name)
SELECT 'ROLE_SOCIAL_WORKER'
WHERE NOT EXISTS (
    SELECT 1 FROM roles WHERE name = 'ROLE_SOCIAL_WORKER'
);