INSERT INTO ROLES (name) VALUES ("ROLE_ADMIN");
INSERT INTO ROLES (name) VALUES ("ROLE_COORDINATOR");
INSERT INTO ROLES (name) VALUES ("ROLE_NUTRITIONIST");
INSERT INTO ROLES (name) VALUES ("ROLE_PSYCHOLOGIST");
INSERT INTO ROLES (name) VALUES ("ROLE_SOCIAL_WORKER");